### ISSUE TITLE
ClpEd25519Blake2B

### ISSUE THREAD

**Issue by kazuser** [Xor-el/CryptoLib4Pascal#10]
Hi!

![ClpEd25519Blake2B pas](https://user-images.githubusercontent.com/3335273/71653363-19b5be80-2d56-11ea-932a-8851323f134e.png)

I'm trying to compile **..\CryptoLib.Samples\Delphi.Samples\UsageSamples.dpr** but can't do it without **ClpEd25519Blake2B.pas**:

![ClpEd25519Blake2B](https://user-images.githubusercontent.com/3335273/71653228-8bd9d380-2d55-11ea-890d-4d6ac1f32e3f.png)

Where I can find it?

Thanks.

**Comment by kazuser** [comment]
![US](https://user-images.githubusercontent.com/3335273/71653581-6221ac00-2d57-11ea-969d-08be6fe2c4fb.png)

OK, I've commented every single line with **Blake**-word and after that the **..\CryptoLib.Samples\Delphi.Samples\UsageSamples.dpr** was compiled successfully.

Hope it's safe :)

**Comment by Xor-el** [comment]
Yes it's safe and my bad, I forgot to update the samples project after some refactorings.
Will do it when I get to my workstation.
Regards.
