### ISSUE TITLE
Consider adding more random nuber generation algorithms

### ISSUE THREAD

**Issue by mWaltari** [Xor-el/CryptoLib4Pascal#12]
There are quite good never algorithms out there, but not too many Delphi/PAscal implementations of them.

If find time and feel that they would benefit library and community, that is my suggestion how to make it better.

**Comment by Xor-el** [comment]
> 
> 
> There are quite good never algorithms out there, but not too many Delphi/PAscal implementations of them.
> 
> If find time and feel that they would benefit library and community, that is my suggestion how to make it better.

First of all, Thanks for suggestions, it's quite valuable but unfortunately this would not be a good fit in this library reason been that this library contains only CSPRNG not just any random number.
meanwhile, I have considered creating a library that implements various random number generators but have been time constrained recently.
