### ISSUE TITLE
Compile error.

### ISSUE THREAD

**Issue by 3874** [Xor-el/CryptoLib4Pascal#14]
** Help me **
When I run CryptoLib.Tests, I got below messages in ClpDigest file.

[dcc32 Error] ClpDigest.pas(178): E2003 Undeclared identifier: 'IXOF'
[dcc32 Error] ClpDigest.pas(181): E2015 Operator not applicable to this operand type
[dcc32 Error] ClpDigest.pas(215): E2003 Undeclared identifier: 'Clone'
[dcc32 Fatal Error] ClpDigestUtilities.pas(268): F2063 Could not compile used unit 'ClpDigest.pas'
Failed

Source code

function TDigest.DoFinal(const output: TCryptoLibByteArray;
  outOff: Int32): Int32;
var
  buf: TCryptoLibByteArray;
  Limit, LXOFSizeInBits: Int32;
begin

  if Supports(FHash, IXOF) then
  begin
    LXOFSizeInBits := (System.Length(output) - outOff) * 8;
    (FHash as IXOF).XOFSizeInBits := LXOFSizeInBits;
    Limit := LXOFSizeInBits shr 3;
  end

Because of it, I can't compile this. Please let me what's the matter.

**Comment by Xor-el** [comment]
Hi, please state which compiler and version you get the error in.
I can't seem to reproduce it locally.
Besides, what exactly do you want to do, I might be able to provide a better approach.

Regards.

**Comment by Xor-el** [comment]
closing issue as no feedback was gotten.
