### ISSUE TITLE
Sample for AES128 Encryption

### ISSUE THREAD

**Issue by combachi** [Xor-el/CryptoLib4Pascal#18]
Hello.

I need AES128, CBC, PKCS7Padding Encryption.
Key & IV already fixed.

sure, i found AES256 encryption function in .Sample,
but I am stupid, I can not change to AES128 encrtypion code.

Please provide a sample for AES128/CBC/PKCS7Padding/(Key & IV already fixed).
(I do not know effect exist or not, anyway Char-Set decide as UTF-8)

Thanks & Regards,

**Comment by Xor-el** [comment]
Hi, the AES type been used is determined automatically by the KeySize.
You can use this Cheatsheet
AES128 = keylength is 16 bytes
AES192 = keylength is 24 bytes
AES256 = keylength is 32 bytes.
