### ISSUE TITLE
GE

### ISSUE THREAD

**Issue by Mocren** [Xor-el/CryptoLib4Pascal#22]
Topic: Get IV in AES256 CBC Decryption.

I´m working with your AES256 CBC Encryption and it´s working great. But i can´t find any option, to get the IV, with i can decrypt the encryptet text with other AES256 programs. How does the IV get calculated? Or how can i get the IV? Some help would be great!

**Comment by Xor-el** [comment]
Hi, you can pass the IV you want when using the TParameterWithIV class and retrieve it from the TParameterWithIV object using the GetIV method.

**Comment by Xor-el** [comment]
please reopen if your issue has not been resolved.
thanks.
