### ISSUE TITLE
Keypair generation and sign/verify using ECDSA + sha1

### ISSUE THREAD

**Issue by DevTeamNoso** [Xor-el/CryptoLib4Pascal#23]
Im trying to create a function for this jobs for my application.
Please, take a look at the question i did in lazarus forums:
https://forum.lazarus.freepascal.org/index.php/topic,53228.0.html
Thanks in advance.

**Comment by Xor-el** [comment]
Hi @DevTeamNoso, Attached is a sample that does what you want. [ECDSASampleLaz.zip](https://github.com/Xor-el/CryptoLib4Pascal/files/5944783/ECDSASampleLaz.zip)

**Comment by DevTeamNoso** [comment]
Thanks for your quick reply. I will check it and let you know.
