### ISSUE TITLE
Test Project does compile (Delphi)

### ISSUE THREAD

**Issue by bnzbnz** [Xor-el/CryptoLib4Pascal#34]
The Test project does not build, Unit "HlpIHash" is missing (used by ClpIDigest, Delphi 11).
Any Help ?

**Comment by ertankucukoglu** [comment]
Hello,

It does compile just fine.

You need to include all necessary directories in your search path. Either project or Delphi Library Path.

Regards,
Ertan

**Comment by bnzbnz** [comment]
Ertan,

 

Would you provide a simple example of signing and verifying with ED25519 :

A Key (private) and a payload as input. If it works I am willing to pay…

 

Thank you,

Please let me know.

Laurent

**Comment by ertankucukoglu** [comment]
Hello,

I'm sure library can do that. Unfortunately I don't know how.

However, you might want to contact with Xor-el as he can help you out.

Regards,
Ertan

**Comment by bnzbnz** [comment]
Hi,

Any idea to how contact him in private ?

Lo.

**Comment by ertankucukoglu** [comment]
Hi,

He should see these messages soon and get in touch with you. Just wait a
day or two.

Regards,
Ertan

Laurent MEYER ***@***.***>, 2 Kas 2022 Çar, 08:34 tarihinde
şunu yazdı:

**Comment by Xor-el** [comment]
Hello @bnzbnz maybe you can provide sample key (public and private) and payload you wish to operate on.
You can also do same via mail as I have responded to you there too.

**Comment by bnzbnz** [comment]
Here you are !

 

Private:

MC4CAQAwBQYDK2VwBCIEIBL22qIQTR8IhjsW85lc31qzZLDyNtKQClHqiNbRddEy

Public:

MCowBQYDK2VwAyEAqNtjQAGYGyVuhZoADbDu32eKsMk/0IY96RNWIVHhWpk=

Payload:

aaaa

 

Thank you so much.

**Comment by bnzbnz** [comment]
It’s also what I saw but

they come directly from ebay, created by eBayR.API.KeyManagement.createSigningKey with a signing  cipher = ‘ED25519’ (Edwards Curve).
