### ISSUE TITLE
I can't find aes/gcm/nopadding ? I searched whole internet and can;t find anything.

### ISSUE THREAD

**Issue by a-nouri** [Xor-el/CryptoLib4Pascal#36]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Xor-el** [comment]
Hello @a-nouri , unfortunately at this time `CrytoLib4Pascal` provides no support for `AES GCM`.
