### ISSUE TITLE
HMAC-SHA256 help needed

### ISSUE THREAD

**Issue by ertankucukoglu** [Xor-el/CryptoLib4Pascal#37]
Hello,

I am using Delphi 11.3 and trying to generate HMAC-SHA256. Samples codes only has single example to HMAC for PascalCoin. I came up with following code and it gives me compile error

```
uses
  ClpIDigest,
  ClpIMac,
  ClpDigestUtilities,
  ClpMacUtilities,
  ClpICipherParameters;

procedure TForm1.Button1Click(Sender: TObject);
var
  DigestMACInstance: IMac;
  Parameters: IChiperParameters; // [dcc32 Error] Unit1.pas(37): E2003 Undeclared identifier: 'IChiperParameters'
  LHMACBytes: TBytes;
begin
  DigestMACInstance := TMacUtilities.GetMac('HMAC-SHA256');
  // I believe Parameters to be assigned with my secret key and data to be hashed here
  DigestMACInstance.Init(Parameters);
  LHMACBytes := DigestMACInstance.DoFinal();
end;

```
I also saw `TMacUtilities` has direct reading of HMAC value which is easier to use in code but my problem is also valid for that use case as I need to pass parameters.

When I check `ClpICipherParameters.pas` it actually has empty interface defined in it.

I could not figure out my mistake. Any help is appreciated.

Thanks & Regards,
Ertan

**Comment by ertankucukoglu** [comment]
I knew I missed something. That did the job.

Thank you.

**Comment by Xor-el** [comment]
You're welcome!
