### ISSUE TITLE
How to convert public and private keys from PKCS#8 format to the hexadecimal arrays used by the library?

### ISSUE THREAD

**Issue by PauloDouglas** [Xor-el/CryptoLib4Pascal#40]
Xor-el, initially I would like to thank you for making your library available. 
Using the example contained in the ED25519Cripto.pas unit, I was able to formulate a function to return the signature, but the input and output are in hexadecimal arrays, but my public and private keys are strings in PKCS#8 format (generated by AsymmetricKeyGenerator-setup- v0.5.3).
How to convert public and private keys from PKCS#8 format to the hexadecimal arrays used by the library?
As for the payload, in ansi format, I also have doubts about how to properly convert it to the hexadecimal arrays used by the library.

Thank you in advance for your help.

Paulo.

**Comment by Xor-el** [comment]
Hello @PauloDouglas my apologies,  just seeing this now.
Must have missed the notifications. 
Have you been able to resolve this?

**Comment by PauloDouglas** [comment]
Oi Xor-el, ainda não. Estou partindo para o desespero e tentando fazer uma DLL em Python kkkk
Agradeceria imensamente se puder me ajudar nisso

**Comment by Xor-el** [comment]
Hello @PauloDouglas the bytes format accepted by my library should be encoded in `DER` format.
this means you have to use an external tool or write some Delphi code to convert your keys from the PKCS#8 format to the native `DER` format supported by my library.

**Comment by PauloDouglas** [comment]
Muito obrigado Xor-el, vou pesquisar aqui e ver como fazer essa conversão!

**Comment by PauloDouglas** [comment]
Grato!
