### ISSUE TITLE
Encrypt integer to another integer and decrypt it back 

### ISSUE THREAD

**Issue by ertankucukoglu** [Xor-el/CryptoLib4Pascal#42]
Hello,

I know that this library is meant to be secure and supports only known to be secure algorithms.

Yet, I need a very simple, very insecure chipper for only obfuscating a 3-4 digit integer number to about the same digit another number (can be a few more digits) and later convert it back to original.

Integer value is something not important but I also do not want it to be plain readable. This will be communicated over the phone and AES or others that I know are making it quite difficult for its purpose.

Thanks & Regards,
Ertan

**Comment by MaslanDo** [comment]
Hi.

Your description of protection level is very poor. If i understand you corretly, you can multiply your number by 3 (or 5, or 7....) , so result will be "few more digits", easy to "later convert it back to original" and still "plain readable".

**Comment by Xor-el** [comment]
Hello @ertankucukoglu like you rightly stated, this library provides only standard encryption algorithms.
You can achieve the obfuscation you want using some simple textbook Xor operations or [Sqids](https://sqids.org/pascal)

**Comment by ertankucukoglu** [comment]
Sqids seems to be good for the job.
Thank you.
